version = 1

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "typescript"
enabled = true

[analyzers.meta]
# Adjust environment or node version if needed
environment = ["nodejs"]

# [issues]
# exclude_patterns = [
#     ".docusaurus/**",
#     "build/**",
#     "node_modules/**"
# ]
