/**
 * The worker body is written as a plain-JS string (no imports, no
 * template-literal nesting) and loaded via a Blob URL, matching the
 * pattern already used in `src/hooks/useConsoleCapture.ts`. This avoids
 * any bundler-specific `new Worker(new URL(...))` wiring and works
 * identically in dev and prod builds.
 *
 * Protocol:
 *   postMessage({ id, algorithmId, size, deadlineMs })
 *   -> { id, status: 'done', timeMs, comparisons, memoryEstimateBytes, liveHeapDeltaBytes | null }
 *   -> { id, status: 'timeout', elapsedMs, estimatedTotalMs, comparisons, comparisonsExpected, memoryEstimateBytes }
 *   -> { id, status: 'error', message }
 */
export function getBenchmarkWorkerSource(): string {
  return [
    "'use strict';",
    "",
    "function mulberry32(seed) {",
    "  return function () {",
    "    seed |= 0; seed = (seed + 0x6D2B79F5) | 0;",
    "    var t = Math.imul(seed ^ (seed >>> 15), 1 | seed);",
    "    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;",
    "    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;",
    "  };",
    "}",
    "",
    "function makeRandomArray(n) {",
    "  var rand = mulberry32(12345);",
    "  var arr = new Array(n);",
    "  for (var i = 0; i < n; i++) arr[i] = Math.floor(rand() * n * 10);",
    "  return arr;",
    "}",
    "",
    "function makeSortedArray(n) {",
    "  var arr = new Array(n);",
    "  for (var i = 0; i < n; i++) arr[i] = i * 2;",
    "  return arr;",
    "}",
    "",
    "// Timeout sentinel thrown from inside the tight loops once the time budget is spent.",
    "function TimeBudgetExceeded(info) { this.info = info; }",
    "",
    "function checkDeadline(deadline, comparisons, comparisonsExpected, startTime) {",
    "  if (performance.now() > deadline) {",
    "    var elapsedMs = performance.now() - startTime;",
    "    var fraction = comparisonsExpected > 0 ? (comparisons / comparisonsExpected) : 0;",
    "    var estimatedTotalMs = fraction > 0 ? elapsedMs / fraction : null;",
    "    throw new TimeBudgetExceeded({",
    "      elapsedMs: elapsedMs,",
    "      comparisons: comparisons,",
    "      comparisonsExpected: comparisonsExpected,",
    "      estimatedTotalMs: estimatedTotalMs,",
    "    });",
    "  }",
    "}",
    "",
    "function bubbleSort(arr, deadline, startTime) {",
    "  var n = arr.length;",
    "  var expected = (n * (n - 1)) / 2;",
    "  var comparisons = 0;",
    "  for (var i = 0; i < n - 1; i++) {",
    "    var swapped = false;",
    "    for (var j = 0; j < n - i - 1; j++) {",
    "      comparisons++;",
    "      if ((comparisons & 8191) === 0) checkDeadline(deadline, comparisons, expected, startTime);",
    "      if (arr[j] > arr[j + 1]) {",
    "        var tmp = arr[j]; arr[j] = arr[j + 1]; arr[j + 1] = tmp;",
    "        swapped = true;",
    "      }",
    "    }",
    "    if (!swapped) break;",
    "  }",
    "  return comparisons;",
    "}",
    "",
    "function selectionSort(arr, deadline, startTime) {",
    "  var n = arr.length;",
    "  var expected = (n * (n - 1)) / 2;",
    "  var comparisons = 0;",
    "  for (var i = 0; i < n - 1; i++) {",
    "    var minIdx = i;",
    "    for (var j = i + 1; j < n; j++) {",
    "      comparisons++;",
    "      if ((comparisons & 8191) === 0) checkDeadline(deadline, comparisons, expected, startTime);",
    "      if (arr[j] < arr[minIdx]) minIdx = j;",
    "    }",
    "    if (minIdx !== i) {",
    "      var tmp = arr[i]; arr[i] = arr[minIdx]; arr[minIdx] = tmp;",
    "    }",
    "  }",
    "  return comparisons;",
    "}",
    "",
    "function insertionSort(arr, deadline, startTime) {",
    "  var n = arr.length;",
    "  var expected = (n * (n - 1)) / 2;",
    "  var comparisons = 0;",
    "  for (var i = 1; i < n; i++) {",
    "    var key = arr[i];",
    "    var j = i - 1;",
    "    while (j >= 0 && arr[j] > key) {",
    "      comparisons++;",
    "      if ((comparisons & 8191) === 0) checkDeadline(deadline, comparisons, expected, startTime);",
    "      arr[j + 1] = arr[j];",
    "      j--;",
    "    }",
    "    arr[j + 1] = key;",
    "  }",
    "  return comparisons;",
    "}",
    "",
    "function mergeSort(arr, deadline, startTime) {",
    "  var n = arr.length;",
    "  var expected = Math.max(1, n * Math.log2(Math.max(2, n)));",
    "  var counter = { comparisons: 0 };",
    "  var buffer = new Array(n);",
    "  function sort(lo, hi) {",
    "    if (hi - lo <= 1) return;",
    "    var mid = (lo + hi) >>> 1;",
    "    sort(lo, mid);",
    "    sort(mid, hi);",
    "    var i = lo, j = mid, k = lo;",
    "    while (i < mid && j < hi) {",
    "      counter.comparisons++;",
    "      if ((counter.comparisons & 8191) === 0) checkDeadline(deadline, counter.comparisons, expected, startTime);",
    "      if (arr[i] <= arr[j]) buffer[k++] = arr[i++]; else buffer[k++] = arr[j++];",
    "    }",
    "    while (i < mid) buffer[k++] = arr[i++];",
    "    while (j < hi) buffer[k++] = arr[j++];",
    "    for (var m = lo; m < hi; m++) arr[m] = buffer[m];",
    "  }",
    "  sort(0, n);",
    "  return counter.comparisons;",
    "}",
    "",
    "function quickSort(arr, deadline, startTime) {",
    "  var n = arr.length;",
    "  var expected = Math.max(1, n * Math.log2(Math.max(2, n)));",
    "  var counter = { comparisons: 0 };",
    "  function partition(lo, hi) {",
    "    var pivot = arr[(lo + hi) >>> 1];",
    "    var i = lo, j = hi;",
    "    while (i <= j) {",
    "      while (true) {",
    "        counter.comparisons++;",
    "        if ((counter.comparisons & 8191) === 0) checkDeadline(deadline, counter.comparisons, expected, startTime);",
    "        if (arr[i] >= pivot) break;",
    "        i++;",
    "      }",
    "      while (true) {",
    "        counter.comparisons++;",
    "        if ((counter.comparisons & 8191) === 0) checkDeadline(deadline, counter.comparisons, expected, startTime);",
    "        if (arr[j] <= pivot) break;",
    "        j--;",
    "      }",
    "      if (i <= j) {",
    "        var tmp = arr[i]; arr[i] = arr[j]; arr[j] = tmp;",
    "        i++; j--;",
    "      }",
    "    }",
    "    return i;",
    "  }",
    "  function sort(lo, hi) {",
    "    if (lo >= hi) return;",
    "    var p = partition(lo, hi);",
    "    sort(lo, p - 1);",
    "    sort(p, hi);",
    "  }",
    "  sort(0, n - 1);",
    "  return counter.comparisons;",
    "}",
    "",
    "function linearSearch(arr, deadline, startTime) {",
    "  var n = arr.length;",
    "  var target = -1; // guaranteed absent -> forces the full worst-case scan",
    "  var comparisons = 0;",
    "  for (var i = 0; i < n; i++) {",
    "    comparisons++;",
    "    if ((comparisons & 16383) === 0) checkDeadline(deadline, comparisons, n, startTime);",
    "    if (arr[i] === target) return comparisons;",
    "  }",
    "  return comparisons;",
    "}",
    "",
    "function binarySearch(arr, deadline, startTime) {",
    "  var n = arr.length;",
    "  var target = -1; // guaranteed absent -> forces the full worst-case walk",
    "  var lo = 0, hi = n - 1, comparisons = 0;",
    "  while (lo <= hi) {",
    "    comparisons++;",
    "    var mid = (lo + hi) >>> 1;",
    "    if (arr[mid] === target) return comparisons;",
    "    if (arr[mid] < target) lo = mid + 1; else hi = mid - 1;",
    "  }",
    "  return comparisons;",
    "}",
    "",
    "var RUNNERS = {",
    "  'bubble-sort': { fn: bubbleSort, gen: makeRandomArray, extraBytesPerElement: 0 },",
    "  'selection-sort': { fn: selectionSort, gen: makeRandomArray, extraBytesPerElement: 0 },",
    "  'insertion-sort': { fn: insertionSort, gen: makeRandomArray, extraBytesPerElement: 0 },",
    "  'merge-sort': { fn: mergeSort, gen: makeRandomArray, extraBytesPerElement: 8 },",
    "  'quick-sort': { fn: quickSort, gen: makeRandomArray, extraBytesPerElement: 0 },",
    "  'linear-search': { fn: linearSearch, gen: makeRandomArray, extraBytesPerElement: 0 },",
    "  'binary-search': { fn: binarySearch, gen: makeSortedArray, extraBytesPerElement: 0 },",
    "};",
    "",
    "self.onmessage = function (e) {",
    "  var msg = e.data;",
    "  var id = msg.id, algorithmId = msg.algorithmId, size = msg.size;",
    "  var deadlineMs = msg.deadlineMs || 4000;",
    "  var runner = RUNNERS[algorithmId];",
    "  if (!runner) {",
    "    self.postMessage({ id: id, status: 'error', message: 'Unknown algorithm: ' + algorithmId });",
    "    return;",
    "  }",
    "  try {",
    "    var heapBefore = (self.performance && self.performance.memory) ? self.performance.memory.usedJSHeapSize : null;",
    "    var arr = runner.gen(size);",
    "    var startTime = performance.now();",
    "    var deadline = startTime + deadlineMs;",
    "    var comparisons = runner.fn(arr, deadline, startTime);",
    "    var timeMs = performance.now() - startTime;",
    "    var heapAfter = (self.performance && self.performance.memory) ? self.performance.memory.usedJSHeapSize : null;",
    "    var memoryEstimateBytes = size * 8 + size * runner.extraBytesPerElement;",
    "    self.postMessage({",
    "      id: id,",
    "      status: 'done',",
    "      timeMs: timeMs,",
    "      comparisons: comparisons,",
    "      memoryEstimateBytes: memoryEstimateBytes,",
    "      liveHeapDeltaBytes: (heapBefore != null && heapAfter != null) ? Math.max(0, heapAfter - heapBefore) : null,",
    "    });",
    "  } catch (err) {",
    "    if (err instanceof TimeBudgetExceeded) {",
    "      var memoryEstimateBytesTo = size * 8 + size * runner.extraBytesPerElement;",
    "      self.postMessage({",
    "        id: id,",
    "        status: 'timeout',",
    "        elapsedMs: err.info.elapsedMs,",
    "        estimatedTotalMs: err.info.estimatedTotalMs,",
    "        comparisons: err.info.comparisons,",
    "        comparisonsExpected: err.info.comparisonsExpected,",
    "        memoryEstimateBytes: memoryEstimateBytesTo,",
    "      });",
    "    } else {",
    "      self.postMessage({ id: id, status: 'error', message: (err && err.message) ? err.message : String(err) });",
    "    }",
    "  }",
    "};",
  ].join("\n");
}
