name: 📚 Documentation
description: Report an issue related to documentation
labels: [documentation, 'docs: algo contributors']
body:
  - type: markdown
    attributes:
      value: |
        This template is strictly used for documentation requests, including:

        - Documenting new topics or features;
        - Elaborating on a specific subject in the DSA content;
        - Updating or fixing existing content;
        - Enhancing code examples or explanations;
        - Anything else that involves documentation but does not change the codebase.

        Before submitting an issue, please ensure:

        - You have checked the existing documentation to confirm the information is missing or needs updating.
        - For issues caused by incorrect behavior in code, use the "bug" template instead.

        If you are confident that your documentation request meets these criteria, you may also submit a pull request directly.

  - type: checkboxes
    attributes:
      label: Have you read the Contributing Guidelines on issues?
      options:
        - label: I have read the [Contributing Guidelines on issues](https://github.com/ajay-dhangar/algo/blob/main/CONTRIBUTING.md).
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the documentation issue is.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you're willing to work on this documentation request, please check the box below. This indicates to the maintainers that you're already working on it.
        If you check the box, please send a pull request within 7 days to avoid reassignment.
      options:
        - label: I'd be willing to address this documentation request myself.
