name: "🚀 Feature Request"
description: "Suggest a new feature or enhancement for Algo."
title: "[Feature]: <Feature Name>"
labels: ["enhancement", "feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature for **Algo**! Please fill out the information below to help us understand your request better.

  - type: input
    id: feature_name
    attributes:
      label: "Feature Name"
      description: "Provide a brief name for the feature you're requesting."
      placeholder: "E.g., Add binary search algorithm visualization"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "Provide a detailed description of the feature. Explain what it does, why it's useful, and any additional context."
      placeholder: "Explain the feature and its use case..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Describe why this feature should be added to Algo. How does it benefit users?"
      placeholder: "Provide the motivation behind this feature..."
    validations:
      required: true

  - type: textarea
    id: implementation_suggestions
    attributes:
      label: "Implementation Suggestions (Optional)"
      description: "Share any suggestions on how this feature could be implemented. Include any libraries or tools that might help."
      placeholder: "Provide implementation suggestions or steps..."

  - type: dropdown
    id: feature_type
    attributes:
      label: "Feature Type"
      description: "Select the type of feature request."
      options:
        - "New Algorithm"
        - "Documentation Enhancement"
        - "UI/UX Improvement"
        - "Performance Optimization"
        - "Other"
    validations:
      required: true

  - type: checkboxes
    id: additional_resources
    attributes:
      label: "Does this feature require additional resources?"
      description: "Check all that apply."
      options:
        - label: "Additional Documentation"
        - label: "Third-Party Libraries"
        - label: "UI/UX Design"
        - label: "Other"
      
  - type: textarea
    id: references
    attributes:
      label: "References (Optional)"
      description: "Provide links to any relevant resources, documentation, or examples that can help understand the feature request."
      placeholder: "Add links to relevant references, resources, or documentation..."

  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to suggest this feature!** Our team will review your request and get back to you soon. 🚀
