import React from 'react';
import GitHubButton from 'react-github-btn';

/**
 * Supported GitHub action types
 */
export type GitHubActionType =
  | 'star'
  | 'sponsor'
  | 'watch'
  | 'fork'
  | 'follow'
  | 'issue'
  | 'discussion';

interface CustomGitHubButtonProps {
  /** Target GitHub URL (repo, profile, issues page, etc.) */
  href: string;
  /** Action type to set default icons, labels, and behavior */
  action: GitHubActionType;
  /** GitHub username or 'owner/repo' path for accessibility labels */
  targetName?: string;
  /** Custom label text. Overrides default label generated by action */
  children?: React.ReactNode;
  /** Toggle showing public counts (stars, forks, etc.) */
  showCount?: boolean;
  /** Button size variant */
  size?: 'small' | 'large';
  /** Color scheme string for light/dark mode support */
  colorScheme?: string;
  /** Override default Octicon icon */
  icon?: string;
  /** Override custom aria-label */
  ariaLabel?: string;
}

/**
 * Preset mapping for default Octicon icons, display labels, and aria-labels.
 */
const ACTION_CONFIG: Record<
  GitHubActionType,
  { icon?: string; label: string; getAriaLabel: (target: string) => string }
> = {
  star: {
    icon: 'octicon-star',
    label: 'Star',
    getAriaLabel: (target) => `Star ${target} on GitHub`,
  },
  sponsor: {
    icon: 'octicon-heart',
    label: 'Sponsor',
    getAriaLabel: (target) => `Sponsor ${target} on GitHub`,
  },
  watch: {
    icon: 'octicon-eye',
    label: 'Watch',
    getAriaLabel: (target) => `Watch ${target} on GitHub`,
  },
  fork: {
    icon: 'octicon-repo-forked',
    label: 'Fork',
    getAriaLabel: (target) => `Fork ${target} on GitHub`,
  },
  follow: {
    icon: undefined, // Follow buttons typically use no icon
    label: 'Follow',
    getAriaLabel: (target) => `Follow ${target} on GitHub`,
  },
  issue: {
    icon: 'octicon-issue-opened',
    label: 'Issue',
    getAriaLabel: (target) => `Issue ${target} on GitHub`,
  },
  discussion: {
    icon: 'octicon-comment-discussion',
    label: 'Discuss',
    getAriaLabel: (target) => `Discuss ${target} on GitHub`,
  },
};

/**
 * A reusable wrapper around `react-github-btn` with sensible defaults.
 */
export const GitHubBtns: React.FC<CustomGitHubButtonProps> = ({
  href,
  action,
  targetName = '',
  children,
  showCount = true,
  size = 'large',
  colorScheme = 'no-preference: light; light: light; dark: dark;',
  icon,
  ariaLabel,
}) => {
  const config = ACTION_CONFIG[action];

  // Resolve values prioritizing explicit props, falling back to predefined configs
  const resolvedIcon = icon ?? config.icon;
  const resolvedAriaLabel = ariaLabel ?? config.getAriaLabel(targetName);
  const resolvedContent = children ?? (action === 'follow' && targetName ? `Follow ${targetName}` : config.label);

  return (
    <GitHubButton
      href={href}
      data-color-scheme={colorScheme}
      data-icon={resolvedIcon}
      data-size={size}
      data-show-count={showCount ? 'true' : undefined}
      aria-label={resolvedAriaLabel}
    >
      {resolvedContent}
    </GitHubButton>
  );
};